spring.application.name=invitation

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/invitation
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

debug=true

# JWT settings
jwt.secret=KsYVvF5Yemg94v3OVzp+w9C3C4ONliSk7ksmAK4axR54KkzE5L+ZTo1XPiMb+8IVAY6j1VVQ9ZtkBeM+V8HtBA==
# (3,600,000 milliseconds) # 1 hour in milliseconds
jwt.expiration=3600000
jwt.issuer=invitation.com